---
- name: Install BugBounty Arsenal
  hosts: dev
  become: yes  # Go install typically does not require elevated privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400  

    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - git
          - vim
          - nano
          - net-tools
          - mlocate
          - zip
          - unzip
          - htop
          - curl
          - tmux
          - openssh-server
          - wget
          - cmake
          - libpcap-dev
          - nmap
          - cewl
          - jq
          - build-essential
          - software-properties-common
          - python3
          - python3-pip
          - openssl
      register: install_packages
      until: install_packages is succeeded