Vagrant.configure("2") do |config|
    (1..3).each do |i|
      config.vm.define "node-0#{i}" do |vm_config|
        vm_config.vm.box = "hashicorp/bionic64"
        vm_config.vm.hostname = "node-0#{i}.local"
        vm_config.vm.network "public_network"
        vm_config.vm.disk :disk, name: "node-0#{i}", size: "20GB"
        vm_config.vm.synced_folder ".", "/vagrant", disabled: true
        vm_config.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 1
        end
  
        vm_config.vm.provision "shell", inline: <<-SHELL
          echo "Running provisioning script..."
          apt-get update
          apt-get upgrade -y
          apt-get install -y ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        SHELL
      end
    end
  end
  